coverage:
  status:
    project:
      default:
        # basic
        target: 80%
        threshold: 5%
        if_ci_failed: error
    patch:
      default:
        target: 80%      # Target for new code in the pull request
        threshold: 0%    # No decrease allowed for patch
ignore:
  - "src/**/templates/**"
