<?php

/**
 * MIT License. This file is part of the Propel package.
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types = 1);

namespace Propel\Generator\Model;

/**
 * Interface for various ID retrieval method types
 * (i.e. auto-increment, sequence, ID broker, etc.).
 */
interface IdMethod
{
    /**
     * Key generation via database-specific ID method
     * (i.e. auto-increment for MySQL, sequence for Oracle, etc.).
     *
     * @var string
     */
    public const NATIVE = 'native';

    /**
     * No RDBMS key generation (keys may be generated by the
     * application).
     *
     * @var string
     */
    public const NO_ID_METHOD = 'none';
}
