<?php

declare(strict_types = 1);

namespace Propel\Generator\Model;

use LogicException;
use Propel\Generator\Platform\PlatformInterface;
use function in_array;
use function strtolower;

/**
 * Interface for various ID retrieval method types
 * (i.e. auto-increment, sequence, ID broker, etc.).
 */
enum IdMethod : string
{
    /**
     * Key generation via database-specific ID method
     * (i.e. auto-increment for MySQL, sequence for Oracle, etc.).
     */
    case NATIVE = 'native';

    /**
     * Example-DDL (MySQL): id integer AUTO_INCREMENT
     */
    case AUTO_INCREMENT = 'auto_increment';

    /**
     * Use generated column.
     *
     * Example-DDL (postgres): id integer GENERATED ALWAYS AS identity
     */
    case IDENTITY = 'identity';

    /**
     * Key based on a sequence.
     *
     * Example-DDL (postgres): id integer DEFAULT nextval('tablename_colname_seq') NOT NULL
     */
    case SEQUENCE = 'sequence';

    /**
     * No RDBMS key generation (keys may be generated by the
     * application).
     */
    case NO_ID_METHOD = 'none';

    /**
     * @param string|null $value
     *
     * @return \Propel\Generator\Model\IdMethod|null
     */
    public static function fromAttribute(string|null $value): self|null
    {
        return !$value ? null : self::tryFrom(strtolower($value));
    }

    /**
     * @param \Propel\Generator\Platform\PlatformInterface|null $platform
     *
     * @throws \LogicException
     *
     * @return bool
     */
    public function usesSequence(PlatformInterface|null $platform = null): bool
    {
        $value = $this === IdMethod::NATIVE && $platform
            ? $platform->getNativeIdMethod()
            : $this;

        return match ($value) {
            IdMethod::SEQUENCE,
            => true,
            IdMethod::NATIVE
            => throw new LogicException('Cannot evaluate meta-value `NATIVE`'),
            default => false,
        };
    }

    /**
     * Check if ID method recommends loading ID before running INSERT.
     *
     * @return bool
     */
    public function isGetIdBeforeInsert(): bool
    {
        return $this === self::SEQUENCE;
    }

    /**
     * Check if generated id can be retrieved only after insert.
     *
     * @return bool
     */
    public function isGetIdAfterInsert(): bool
    {
        return in_array($this, [self::AUTO_INCREMENT, self::IDENTITY, self::NATIVE]);
    }
}
